# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(null=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], null=True)),
                ('login', models.CharField(max_length=10, unique=True)),
                ('tipo', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizada', models.DateField(default=django.utils.timezone.now)),
                ('data_refazer', models.DateField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dobra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tricipes', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('bicipes', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('suprailiaca', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('toracica', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('axilarmedia', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('panturrilhamedia', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('avaliacaofisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.AvaliacaoFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Perimetria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('pescoco', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('abdome', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('bicipesdireito', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('bicipesesquedo', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tricipesdireito', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tricipesesquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('antebracodireito', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('antebracoesquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('coxadireita', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('coxaesquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('panturrilhadireta', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('panturrilhaesquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('avaliacaofisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.AvaliacaoFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('repeticao', models.IntegerField()),
                ('dia', models.CharField(max_length=7)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='serie',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Treino'),
        ),
    ]
