# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20170217_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaAnamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAnamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('observacao', models.TextField()),
                ('avaliacaofisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.AvaliacaoFisica')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.PerguntaAnamnese')),
            ],
        ),
    ]
