# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_perguntaanamnese_respostaanamnese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobra',
            name='avaliacaofisica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academia.AvaliacaoFisica'),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='avaliacaofisica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academia.AvaliacaoFisica'),
        ),
    ]
