# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_auto_20170218_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaanamnese',
            name='avaliacaofisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_anamnese', to='academia.AvaliacaoFisica'),
        ),
        migrations.AlterField(
            model_name='respostaanamnese',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respostaanamnese',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='resposta'),
        ),
    ]
