# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_auto_20170218_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobra',
            name='metodo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacaofisica',
            name='pessoa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='abdominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='avaliacaofisica',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='academia.AvaliacaoFisica'),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='axilarmedia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='bicipes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='coxa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='panturrilhamedia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dobra',
            name='subescapular',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='suprailiaca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='toracica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='tricipes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='abdome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='antebracodireito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='antebracoesquerdo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='avaliacaofisica',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='academia.AvaliacaoFisica'),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='bicipesdireito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='bicipesesquedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='cintura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='coxadireita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='coxaesquerda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='panturrilhadireta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='panturrilhaesquerda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='pescoco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='quadril',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='torax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='tricipesdireito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='tricipesesquerdo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='respostaanamnese',
            name='avaliacaofisica',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_anamnese', to='academia.AvaliacaoFisica'),
        ),
    ]
