# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 14:16
from __future__ import unicode_literals

import academia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_auto_20170219_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofisica',
            name='data_refazer',
            field=models.DateField(default=academia.models.refazer_dia),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='metodo',
            field=models.IntegerField(choices=[(0, 'Durnin Womersley 1974'), (1, 'Jackson, Pollock e Ward 1984')]),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
