# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_auto_20170316_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobra',
            name='abdominal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='axilarmedia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='bicipes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='coxa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='metodo',
            field=models.CharField(choices=[('jackson_pollock_ward_1980', 'Jackson, Pollock e Ward 1980 (mulheres, 18 a 55 anos)'), ('jackson_pollock_1978', 'Jackson, Pollock 1984'), ('pestroski_1995_homem', 'Pestroski 1995 (homens, 18 a 61 anos)'), ('durnin_womersley_1974', 'Durnin Womersley 1974'), ('pestroski_1995_mulher', 'Pestroski 1995 (mulheres, 18 a 61 anos)'), ('pollock_schimidt_jackson_1980', 'Pollock, Schimidt e Jackson 1980 (adultos)'), ('jackson_pollock_ward_1984', 'Jackson, Pollock e Ward 1984')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='panturrilhamedia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='resultado',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='subescapular',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='suprailiaca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='toracica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dobra',
            name='tricipes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='abdome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='antebracodireito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='antebracoesquerdo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='bicipesdireito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='bicipesesquedo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='cintura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='coxadireita',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='coxaesquerda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='panturrilhadireta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='panturrilhaesquerda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='pescoco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='quadril',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='torax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='tricipesdireito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perimetria',
            name='tricipesesquerdo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='repeticao',
            field=models.IntegerField(verbose_name='Repetição'),
        ),
    ]
