# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0012_auto_20170320_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaofisica',
            options={'ordering': ('data_realizada',)},
        ),
        migrations.AlterField(
            model_name='dobra',
            name='metodo',
            field=models.CharField(choices=[('boleau_et_al_1985', 'Boleau et ali 1985 (meninos e meninas)'), ('deurenberg_et_al_1990', 'Deurenberg et ali 1990 (meninos e meninas)'), ('durnin_rahman_1967_adolescente', 'Durnin & Rahman 1967 (adolescentes)'), ('durnin_rahman_1967_homem_jovem', 'Durnin & Rahman 1967 (jovens)'), ('durnin_womersley_1974_homem', 'Durnin & Womersley 1974 (homens, 17 a 72 anos)'), ('durnin_womersley_1974_mulher', 'Durnin & Womersley 1974 (mulhers, 16 a 68 anos)'), ('guedes_1995_homem', 'Guedes 1995 (homens, estudantes universitários)'), ('guedes_1995_mulher', 'Guedes 1995 (mulheres, estudantes universitárias)'), ('jackson_pollock_1978', 'Jackson & Pollock 1984 (homens, 18 a 61 anos)'), ('jackson_pollock_ward_1980', 'Jackson, Pollock e Ward 1980 (mulheres, 18 a 55 anos)'), ('jackson_pollock_ward_1984', 'Jackson, Pollock & Ward 1984 (homens)'), ('katch_mcardle_1973', 'Katch & McArdle 1973 (homens, estudantes universitários)'), ('katch_mcardle_1973_mulher', 'Katch & McArdle 1973 (mulheres, estudantes universitários)'), ('nagamine_suzuki_1967', 'Nagamine & Suzuki 1964 (japoneses de 18 a 27 anos)'), ('pariskova_1961', 'Pariskova 1961 (meninas brancas ou negras, 9 a 16 anos)'), ('petroski_1995_homem', 'Petroski 1995 (homens, 18 a 61 anos)'), ('petroski_1995_mulher', 'Petroski 1995 (mulheres, 18 a 61 anos)'), ('pollock_et_al_homem_jovem', 'Pollock et ali 1976 (homens jovens)'), ('pollock_et_al_homem_meia_idade', 'Pollock et ali 1976 (homens de meia-idade)'), ('pollock_et_al_mulher_jovem', 'Pollock et ali 1976 (mulheres jovens)'), ('pollock_schmidt_jackson_1980', 'Pollock, Schmidt e Jackson 1980 (adultos)'), ('slaugter_et_al_1988_brancos', 'Slaughter et ali 1988 (meminos brancos, dobras <= 35mm)'), ('slaugter_et_al_1988_brancos_e_negros', 'Slaughter et ali 1988 (meninos brancos e negros)'), ('slaugter_et_al_1988_brancos_e_negros_2', 'Slaughter et ali 1988 (meninos brancos e negros, dobras > 35mm)'), ('slaugter_et_al_1988_meninas', 'Slaughter et ali 1988 (meninas brancas ou negras, dobras <= 35mm)'), ('slaugter_et_al_1988_meninas_2', 'Slaughter et ali 1988 (meninas brancas ou negras, dobras > 35mm)'), ('slaugter_et_al_1988_meninas_3', 'Slaughter et ali 1988 (meninas brancas ou negras)'), ('slaugter_et_al_1988_negros', 'Slaughter et ali 1988 (meninos negros, dobras <= 35mm)'), ('sloan_1967', 'Sloan 1967 (homens, estudantes universitários de 18 a 26 anos)'), ('sloan_1967_mulher', 'Sloan 1967 (mulheres, estudantes universitárias de 17 a 25 anos)'), ('wilmore_behnke', 'Wilmore & Behnke 1969 (homens, estudantes universitários de 17 a 37 anos)'), ('wilmore_behnke_mulher', 'Wilmore & Behnke 1969 (mulheres, estudantes universitários de 18 a 48 anos)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(3, 'Administrador'), (1, 'Aluno'), (2, 'Treinador')], default=1),
        ),
    ]
