# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_auto_20170419_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
