# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 12:17
from __future__ import unicode_literals

import academia.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0014_treino_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_fim',
            field=models.DateField(default=academia.models.refazer_dia, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
