# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_auto_20170510_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobra',
            name='metodo',
            field=models.CharField(choices=[('boleau_et_al_1985', 'Boileau et alii 1985 (meninos e meninas, 8 a 17 anos) '), ('deurenberg_et_al_1990', 'Deurenberg et alii 1990 (meninos e meninas, Púberes)'), ('durnin_rahman_1967_adolescente', 'Durnin & Rahman 1967 (adolescentes)'), ('durnin_rahman_1967_homem_jovem', 'Durnin & Rahman 1967 (jovens)'), ('durnin_womersley_1974_homem', 'Durnin & Womersley 1974 (homens, 17 a 72 anos)'), ('durnin_womersley_1974_mulher', 'Durnin & Womersley 1974 (mulhers, 16 a 68 anos)'), ('guedes_1995_homem', 'Guedes 1985 (homens, estudantes universitários, 17 a 27 anos)'), ('guedes_1995_mulher', 'Guedes 1985 (mulheres, estudantes universitárias, 17 a 29 anos)'), ('jackson_pollock_ward_1980', 'Jackson, Pollock e Ward 1980 (mulheres, 18 a 55 anos)'), ('jackson_pollock_ward_1984', 'Jackson & Pollock 1978 (homens, 18 a 61 anos)'), ('katch_mcardle_1973', 'Katch & McArdle 1973 (homens, estudantes universitários)'), ('katch_mcardle_1973_mulher', 'Katch & McArdle 1973 (mulheres, estudantes universitários)'), ('nagamine_suzuki_1967', 'Nagamine & Suzuki 1964 (japoneses de 18 a 27 anos)'), ('pariskova_1961', 'Pariskova 1961 (meninas brancas ou negras, 9 a 16 anos)'), ('petroski_1995_homem', 'Petroski 1995 (homens, 18 a 61 anos)'), ('petroski_1995_mulher', 'Petroski 1995 (mulheres, 18 a 61 anos)'), ('pollock_et_al_homem_jovem', 'Pollock et alii 1976 (homens jovens)'), ('pollock_et_al_homem_meia_idade', 'Pollock et alii 1976 (homens de meia-idade)'), ('pollock_et_al_mulher_jovem', 'Pollock et alii 1975 (mulheres jovens)'), ('pollock_schmidt_jackson_1980', 'Pollock, Schmidt e Jackson 1980 (Mulheres adultas)'), ('slaugter_et_al_1988_brancos', 'Slaughter et ali 1988 (meminos brancos, dobras <= 35mm)'), ('slaugter_et_al_1988_brancos_e_negros', 'Slaughter et ali 1988 (meninos brancos e negros)'), ('slaugter_et_al_1988_brancos_e_negros_2', 'Slaughter et ali 1988 (meninos brancos e negros, dobras > 35mm)'), ('slaugter_et_al_1988_meninas', 'Slaughter et alii 1988 (meninas brancas ou negras, dobras <= 35mm)'), ('slaugter_et_al_1988_meninas_2', 'Slaughter et alii 1988 (meninas brancas ou negras, dobras > 35mm)'), ('slaugter_et_al_1988_meninas_3', 'Slaughter et alii 1988 (meninas brancas ou negras)'), ('slaugter_et_al_1988_negros', 'Slaughter et ali 1988 (meninos negros, dobras <= 35mm)'), ('sloan_1967', 'Sloan 1967 (homens, estudantes universitários de 18 a 26 anos)'), ('sloan_1967_mulher', 'Sloan 1962 (mulheres, estudantes universitárias de 17 a 25 anos)'), ('wilmore_behnke', 'Wilmore & Behnke 1969 (homens, estudantes universitários de 17 a 37 anos)'), ('wilmore_behnke_mulher', 'Wilmore & Behnke 1970 (mulheres, estudantes universitários de 18 a 48 anos)')], max_length=50),
        ),
    ]
